splittingalg = "round-robin"

[[connections.connections]]

transport = "lyrebird"
args = ["", ""]
cert = "xxx"
bridge = "yyy"

[[connections.connections]]

transport = "lyrebird"
args = ["", ""]
cert = "xxx"
bridge = "yyy"


